### ISSUE TITLE
Expose chairLiftNames using a function

### ISSUE THREAD

**Issue by RRK1000** [RRK1000/OSMDashboard-Winter-2024-SOEN-6431#25]

**Comment by AkhilaReddy14** [comment]
**Issue:** Exposing the Chair Lift Names to facilitate future use cases where chair lift names are required.
**Solution:** Adding a method named getChairLiftNames() to the ChairLift class, which iterates over the list of ChairLiftElements stored in the class and extracts the names from their associated ChairLiftTags.

[Code changes ](https://github.com/RRK1000/OSMDashboard-Winter-2024-SOEN-6431/pull/33)
